ALTER TABLE J  
DROP COLUMN CITY;

CREATE TABLE EMP (  
EMP_NO INT PRIMARY KEY,  
ENMAE VARCHAR(20) UNIQUE,  
JOB VARCHAR(15),  
SALARY INT NOT NULL,  
DEPT_NO INT, 
CONSTRAINT CHCK_JOB CHECK (JOB='PROF' OR JOB='AP' OR JOB= 'LECT')  
);

CREATE TABLE DEPT( 
DEPT_NO INT PRIMARY KEY, 
DNAME VARCHAR(10), 
CONSTRAINT CHCK_DNAME CHECK(DNAME='ACC' OR DNAME='COMP' OR DNAME='ELECT') 
);

CREATE TABLE S( 
SNO INT PRIMARY KEY, 
SNMAE VARCHAR(15), 
CITY VARCHAR(15) 
);

CREATE TABLE P( 
PNO INT PRIMARY KEY, 
PNMAE VARCHAR(15), 
COLOR VARCHAR(15) 
);

CREATE TABLE J( 
JNO INT PRIMARY KEY, 
JNMAE VARCHAR(15), 
CITY VARCHAR(15) 
);

INSERT INTO EMP VALUES(102003200, 'PRATEEK', 'AP',175000,123);

INSERT INTO EMP VALUES(102003201, 'DEEVANG', 'LECT',150000,122);

INSERT INTO EMP VALUES(102003202, 'YUVRAJ', 'LECT',200000,111);

INSERT INTO EMP VALUES(102003198, 'HRIDAY', 'STUDENT',0,121);

INSERT INTO DEPT VALUES(122,'ELEC');

INSERT INTO DEPT VALUES(123,'COMP');

INSERT INTO DEPT VALUES(111,'ACC');

INSERT INTO DEPT VALUES(122,'ELECT');

ALTER TABLE S 
ADD FOREIGN KEY (SNO) 
REFERENCES S(SNO) 
ON DELETE SET NULL);

INSERT INTO S VALUES(2,'HARMAN','PATIALA');

INSERT INTO S VALUES(3,'NRIP','SANGRUR');

INSERT INTO S VALUES(4,'VANEET','MANSA');

INSERT INTO P VALUES(111,'NUT','GREY');

INSERT INTO P VALUES(222,'BOLT','BLACK');

INSERT INTO P VALUES(333,'SCREW DRIVER','RED');

INSERT INTO P VALUES(444,'HAMMER','BROWN');

INSERT INTO J VALUES(11,'HALLA BOL', 'AMRITSAR');

INSERT INTO J VALUES(22,'PROJECT', 'PATIALA');

INSERT INTO J VALUES(33,'FIRST ', 'CHANDIGARH');

INSERT INTO J VALUES(44,'HELLO PROJECT', 'LUDHIANA');

INSERT INTO SPJ VALUES(1, 111, 11, 1000);

INSERT INTO SPJ VALUES(2, 222, 22, 1500);

INSERT INTO SPJ VALUES(3, 333, 33, 700);

INSERT INTO SPJ VALUES(4, 444, 44, 2000);

DESC EMP


DESC DEPT


DESC S


DESC P


DESC J


DESC SPJ


SELECT * FROM USER_CONSTRAINTS 
WHERE TABLE NAME='EMP';

select CONSTRAINT from user_constraints where table_name = 'EMP';

ALTER TABLE EMP 
DROP CONSTRAINT EMP;

ALTER TABLE EMP 
MODIFY ENAME VARCHAR(100);

ALTER TABLE EMP 
MODIFY ENMAE CHAR(100);

ALTER TABLE DEPT 
MODIFY DNAME VARCHAR2(100);

ALTER TABLE EMP 
ADD COMM NUMBER(20);

ALTER TABLE J 
DROP CITY;

CREATE DUPLICATE_EMP 
AS (SELECT * FROM EMP);

ALTER TABLE EMP 
DROP UNIQUE ENMAE;

ALTER TABLE DEPT 
DROP FOREIGN KEY (DEPT_NO);

ALTER TABLE EMP 
SET NAME='VISHNU KHOKHAR' AND JOB='AP' 
WHERE EMP_NO=102003199;

DELETE FROM EMP 
WHERE DEPT='COMP';

DROP TABLE DEPT


DROP TABLE DUPLICATE_DEPT


desc spj


ALTER TABLE J 
ADD COLUMN CITY;

ALTER TABLE S 
DELETE COLUMN CITY;

ALTER TABLE S 
DROP COLUMN CITY;

CREATE TABLE DUP_EMP AS(SELECT * FROM EMP);

CREATE TABLE DUP_DEPT(DEPTNO,DEPTNAME) AS(SELECT * FROM DEPT);

CREATE TABLE DUP_S(NUMBR,NAMES,DISTRICT) AS(SELECT * FROM S);

CREATE TABLE DEPT(  
DEPT_NO INT PRIMARY KEY,  
DNAME VARCHAR(10),  
CONSTRAINT CHCK_DNAME CHECK(DNAME='ACC' OR DNAME='COMP' OR DNAME='ELECT')  
);

CREATE TABLE DUP_DEPT(DEPTNO,DEPTNAME) AS (SELECT * FROM DEPT);

UPDATE EMP 
SET ENMAE='VISHNU KHOKHAR' , JOB='PROF' 
WHERE EMP_NO=102003199;

UPDATE EMP 
ADD CONSTRAINT UNIQUE (ENMAE);

ALTER TABLE DEPT 
ADD CONSTRAINT DEPTNO_FK FOREIGN KEY DEPT_NO REFERENCES DEPT(DEPT_NO);

ALTER TABLE DEPT 
ADD CONSTRAINT (DEPTNO_FK FOREIGN KEY (DEPT_NO) REFERENCES DEPT(DEPT_NO);

ALTER TABLE EMP 
ADD CONSTRAINT (UNIQUE) TO ENMAE;

ALTER TABLE EMP 
ADD UNIQUE (ENMAE);

ALTER TABLE EMP 
DROP CONSTRAINT (UNIQUE);

ALTER TABLE EMP 
DROP CONSTRAINT (UNIQUE);

ALTER TABLE EMP 
DROP CONSTRAINT UNIQUE (ENMAE);

ALTER TABLE EMP 
ADD UNIQUE EMP_NO;

ALTER TABLE EMP 
ADD UNIQUE (EMP_NO);

ALTER TABLE EMP 
ADD UNIQUE (ENMAE);

ALTER TABLE EMP 
DROP UNIQUE (ENMAE);

ALTER TABLE EMP 
ADD FOREIGN KEY(DEPT_NO);

ALTER TABLE EMP 
ADD FOREIGN KEY(DEPT_NO)  
REFERENCES EMP(DEPT_NO);

ALTER TABLE EMP 
ADD FOREIGN KEY(JOB)  
REFERENCES EMP(JOB);

ALTER TABLE S 
DROP FOREIGN KEY (SNO);

ALTER TABLE S 
DROP FOREIGN KEY S(SNO);

ALTER TABLE S 
ADD  CONSTRAINT SNO_FK
FOREIGN KEY(SNO)  
REFERENCES S(SNO);

ALTER TABLE S  
ADD  CONSTRAINT SNO_FK 
FOREIGN KEY(SNO)   
REFERENCES S(SNO);

ALTER TABLE S  
DROP FOREIGN KEY SNO_FK;

ALTER TABLE S  
DROP FOREIGN KEY (SNO_FK);

ALTER TABLE S  
DROP CONSTRAINT (SNO_FK);

ALTER TABLE S  
DROP CONSTRAINT SNO_FK;

ALTER TABLE S  
DROP CONSTRAINT (SNO_FK);

DESC S 


ALTER TABLE S 
ADD CONSTRAINT SNO_FK 
FOREIGN KEY (SNO) 
REFERENCES S(SNO);

ALTER TABLE S 
DROP CONSTRAINT (SNO_FK);

ALTER TABLE S 
DROP CONSTRAINT (SNO_FK);

ALTER TABLE S 
DROP FOREIGN KEY (SNO);

CREATE TABLE EMP (  
EMP_NO INT PRIMARY KEY,  
ENMAE VARCHAR(20) UNIQUE,  
JOB VARCHAR(15),  
SALARY INT NOT NULL,  
DEPT_NO INT, 
CONSTRAINT CHCK_JOB CHECK (JOB='PROF' OR JOB='AP' OR JOB= 'LECT')  
);

CREATE TABLE DEPT( 
DEPT_NO INT PRIMARY KEY, 
DNAME VARCHAR(10), 
CONSTRAINT CHCK_DNAME CHECK(DNAME='ACC' OR DNAME='COMP' OR DNAME='ELECT') 
);

CREATE TABLE S( 
SNO INT PRIMARY KEY, 
SNMAE VARCHAR(15), 
CITY VARCHAR(15) 
);

CREATE TABLE P( 
PNO INT PRIMARY KEY, 
PNMAE VARCHAR(15), 
COLOR VARCHAR(15) 
);

CREATE TABLE J( 
JNO INT PRIMARY KEY, 
JNMAE VARCHAR(15), 
CITY VARCHAR(15) 
);

INSERT INTO EMP VALUES(102003200, 'PRATEEK', 'AP',175000,123);

INSERT INTO EMP VALUES(102003201, 'DEEVANG', 'LECT',150000,122);

INSERT INTO EMP VALUES(102003202, 'YUVRAJ', 'LECT',200000,111);

INSERT INTO EMP VALUES(102003198, 'HRIDAY', 'STUDENT',0,121);

INSERT INTO DEPT VALUES(122,'ELEC');

INSERT INTO DEPT VALUES(123,'COMP');

INSERT INTO DEPT VALUES(111,'ACC');

INSERT INTO DEPT VALUES(122,'ELECT');

ALTER TABLE S 
ADD FOREIGN KEY (SNO) 
REFERENCES S(SNO) 
ON DELETE SET NULL);

INSERT INTO S VALUES(2,'HARMAN','PATIALA');

INSERT INTO S VALUES(3,'NRIP','SANGRUR');

INSERT INTO S VALUES(4,'VANEET','MANSA');

INSERT INTO P VALUES(111,'NUT','GREY');

INSERT INTO P VALUES(222,'BOLT','BLACK');

INSERT INTO P VALUES(333,'SCREW DRIVER','RED');

INSERT INTO P VALUES(444,'HAMMER','BROWN');

INSERT INTO J VALUES(11,'HALLA BOL', 'AMRITSAR');

INSERT INTO J VALUES(22,'PROJECT', 'PATIALA');

INSERT INTO J VALUES(33,'FIRST ', 'CHANDIGARH');

INSERT INTO J VALUES(44,'HELLO PROJECT', 'LUDHIANA');

INSERT INTO SPJ VALUES(1, 111, 11, 1000);

INSERT INTO SPJ VALUES(2, 222, 22, 1500);

INSERT INTO SPJ VALUES(3, 333, 33, 700);

INSERT INTO SPJ VALUES(4, 444, 44, 2000);

DESC EMP


DESC DEPT


DESC S


DESC P


DESC J


DESC SPJ


SELECT * FROM USER_CONSTRAINTS 
WHERE TABLE NAME='EMP';

select CONSTRAINT from user_constraints where table_name = 'EMP';

ALTER TABLE EMP 
DROP CONSTRAINT EMP;

ALTER TABLE EMP 
MODIFY ENAME VARCHAR(100);

ALTER TABLE EMP 
MODIFY ENMAE CHAR(100);

ALTER TABLE DEPT 
MODIFY DNAME VARCHAR2(100);

ALTER TABLE EMP 
ADD COMM NUMBER(20);

ALTER TABLE J 
DROP CITY;

CREATE DUPLICATE_EMP 
AS (SELECT * FROM EMP);

ALTER TABLE EMP 
DROP UNIQUE ENMAE;

ALTER TABLE DEPT 
DROP FOREIGN KEY (DEPT_NO);

ALTER TABLE EMP 
SET NAME='VISHNU KHOKHAR' AND JOB='AP' 
WHERE EMP_NO=102003199;

DELETE FROM EMP 
WHERE DEPT='COMP';

DROP TABLE DEPT


DROP TABLE DUPLICATE_DEPT


desc spj


