SELECT TABLE student(STUDENT_ID INT PRIMARY KEY, 
STUDENT_NAME VARCHAR(20), 
BRANCH VARCHAR(20));

SELECT TABLE student(STUDENT_ID INT PRIMARY KEY,STUDENT_NAME VARCHAR(20),BRANCH VARCHAR(20));

CREATE TABLE STUDENT(ROLL_NUMBER NUMBER(25), NAME VARCHAR(50), DOB DATE, GENDER VARCHAR(50),CLASS VARCHAR(20), COLLEGE VARCHAR(50), CITY VARCHAR(50),MARKS NUMBER(25));

CREATE TABLE student(STUDENT_ID INT PRIMARY KEY,STUDENT_NAME VARCHAR(20),BRANCH VARCHAR(20));

CREATE TABLE student1(STUDENT_ID INT PRIMARY KEY,STUDENT_NAME VARCHAR(20),BRANCH VARCHAR(20));

CREATE TABLE student1(STUDENT_ID INT PRIMARY KEY,STUDENT_NAME VARCHAR(20),BRANCH VARCHAR(20));

CREATE TABLE student1(STUDENT_ID INT PRIMARY KEY,STUDENT_NAME VARCHAR(20),BRANCH VARCHAR(20));

DESCRIBE student1 


INSERT INTO student1(1,'shady','coe');

INSERT INTO student1 VALUES(1,'shady','coe');

INSERT INTO student1 VALUES(2,'EMINEM','ENC');

INSERT INTO student1(student_id,student_name) VALUES(3,'HONEY ');

SELECT * FROM student1 
;

UPDATE student1 
SET BRANCH='COMPUTER' 
WHERE BRANCH='coe';

SELECT * FROM STUDENT;

SELECT * FROM STUDENT1;

 DELETE FROM student1  
 WHERE STUDENT_NAME='HONEY';

 DELETE FROM student1  
 WHERE STUDENT_NAME='HONEY';

SELECT * FROM student1;

DELETE FROM student1 
WHERE STUDENT_NAME='HONEY';

DELETE FROM student1 
WHERE STUDENT_ID='3';

SELECT * FROM STUDENT1;

SELECT STUDENT_NAME FROM STUDENT1;

SELECT * FROM STUDENT1 
ORDER BY DESC 
;

SELECT BRANCH FROM STUDENT1 
ORDER BY DESC 
;

SELECT BRANCH FROM STUDENT1 
ORDER BY DESC;

SELECT BRANCH FROM STUDENT1 
ORDER BY BRANCH DESC;

SELECT * FROM STUDENT1 
ORDER BY BRANCH DESC;

INSERT INTO student1 VALUES(3, 'YOYO', 'MECH');

INSERT INTO student1 VALUES(3, 'YOYO', 'BIO');

INSERT INTO student1 VALUES(4, 'MIKA', 'ECE');

INSERT INTO student1 VALUES(5, 'NEHA', 'COE');

INSERT INTO student1 VALUES(6, 'ARIJIT', 'MECH');

SELECT * FROM  STUDENT1 
;

SELECT * FROM  STUDENT1 
BY STUDENT_ID DESC 
;

SELECT * FROM  STUDENT1 
ORDER BY STUDENT_ID DESC 
;

UPDATE STUDENT1  
SET BRANCH='MECHANIACL;

WHERE BRANCH='MECH' 


UPDATE STUDENT1  
SET BRANCH='MECHANIACL' 
WHERE BRANCH='MECH' 
;

SELECT * FROM STUDENT1 
;

